files:
  - source: /messages.pot
    translation: /%locale_with_underscore%/LC_MESSAGES/messages.po
pull_request_title: '[Automated] Crowdin synchronization'
pull_request_labels:
  - crowdin
targets:
  - name: Hestiacp
    sources:
      - /hestiacp.pot
    file: /src/%two_letters_code%/LC_MESSAGES/hestiacp.po
    format: po-export
