on:
  push:
    branches:
      - main
    ignore_paths:
      - "**/*.mo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install gettext extension
      run: sudo apt-get update && sudo apt-get install gettext
    - name: Generate .mo files
      run: |
        for po_file in $(find . -name "*.po"); do
          dirname=$(dirname $po_file)
          filename=$(basename $po_file .po)
          msgfmt $po_file -o "$dirname/$filename.mo"
        done
    - name: Add .mo files to git
      run: git add .
    - name: Commit and push .mo files
      uses: actions/github-script@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          git commit -m "Automated .mo file generation"
          git push
